name: Inertia
version: ${project.version}
main: com.ladakx.inertia.InertiaSpigotPlugin
api-version: '1.21'
author: Ladakx
description: A Minecraft plugin that integrates the Jolt Physics engine.
website: https://github.com/ladakx/Inertia
# The 'libraries' section is no longer needed as Jolt is now shaded into the plugin JAR.

