link:
  sync:
    position: true
    rotation: true
  entities:
    display:
      type: BLOCK_DISPLAY
      block: IRON_BARS
      scale: "0.35 0.7 0.35"
      rotate-translation: true
      interpolation-duration: 2
      teleport-duration: 2

