name: inertia-test-tnt
main: com.ladakx.inertia.test.tnt.InertiaTestTntPlugin
version: 1.0-DEV
api-version: "1.16"
depend: [ Inertia ]
commands:
  ittnt:
    description: Spawn Inertia test TNT (via API)
    usage: /ittnt spawn [fuseTicks] [force] [radius]
    permission: inertia.test.tnt
permissions:
  inertia.test.tnt:
    default: op

