tnt:
  sync:
    position: true
    rotation: true
  entities:
    display:
      type: BLOCK_DISPLAY
      block: TNT
      rotate-translation: true
      interpolation-duration: 2
      teleport-duration: 2

