package com.ladakx.inertia.api.capability;

public enum ApiCapability {
    RENDERING,
    JOLT_NATIVE_ACCESS,
    PHYSICS_SHAPE_BOX,
    PHYSICS_SHAPE_SPHERE,
    PHYSICS_SHAPE_CAPSULE,
    PHYSICS_SHAPE_CYLINDER,
    PHYSICS_SHAPE_TAPERED_CAPSULE,
    PHYSICS_SHAPE_TAPERED_CYLINDER,
    PHYSICS_SHAPE_CONVEX_HULL,
    PHYSICS_SHAPE_COMPOUND,
    PHYSICS_SHAPE_CUSTOM,
    INTERACTION_ADVANCED
}
