name: inertia-test-bodies
main: com.ladakx.inertia.test.bodies.InertiaTestBodiesPlugin
version: 1.0-DEV
api-version: "1.16"
depend: [ Inertia ]
commands:
  itb:
    description: Spawn Inertia test bodies (via API)
    usage: /itb spawn <preset>
    permission: inertia.test.bodies
permissions:
  inertia.test.bodies:
    default: op

