name: Build & Release Native Libraries

on:
  push:
    tags:
      - 'v*' # Run  this workflow when a tag like v1.0.0 is pushed

jobs:
  build-natives:
    name: Build for ${{ matrix.os }} (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            artifact_name: inertia-native-linux-x86_64
            lib_name: libinertia_native.so
          - os: ubuntu-latest
            arch: aarch64
            artifact_name: inertia-native-linux-aarch64
            lib_name: libinertia_native.so
          - os: windows-latest
            arch: x86_64
            artifact_name: inertia-native-windows-x86_64
            lib_name: inertia_native.dll
          - os: macos-latest # This will be an x86_64 build due to GitHub runner limitations
            arch: x86_64
            artifact_name: inertia-native-darwin-x86_64
            lib_name: libinertia_native.dylib
          - os: macos-latest # For Apple Silicon
            arch: aarch64
            artifact_name: inertia-native-darwin-aarch64
            lib_name: libinertia_native.dylib

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check for Jolt CMakeLists.txt
        run: ls -l ${{ github.workspace }}/Jolt/CMakeLists.txt || echo "Jolt/CMakeLists.txt not found"

      - name: Set up cross-compilation for Linux aarch64
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-aarch64-linux-gnu

      - name: Create Build Directory
        run: cmake -E make_directory ${{ github.workspace }}/native/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{ github.workspace }}/native/build
        run: |
          # Base CMake command
          CMAKE_CMD="cmake .."
          
          # Add toolchain for Linux aarch64 cross-compile
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.arch }}" == "aarch64" ]]; then
            CMAKE_CMD="$CMAKE_CMD -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++"
          fi
          
          # Add target for macOS Apple Silicon
          if [[ "${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "aarch64" ]]; then
              CMAKE_CMD="$CMAKE_CMD -DCMAKE_OSX_ARCHITECTURES=arm64"
          fi
          
          echo "Running CMake command: $CMAKE_CMD"
          $CMAKE_CMD


      - name: Build Native Library
        working-directory: ${{ github.workspace }}/native/build
        shell: bash
        run: cmake --build . --config Release

      - name: Archive native library
        shell: bash
        run: |
          cd ${{ github.workspace }}/native/build
          # Create a directory for the artifact
          mkdir -p artifact
          # Move the compiled library into it
          mv ${{ matrix.lib_name }} artifact/
          # Create a zip archive
          cd artifact
          zip ../${{ matrix.artifact_name }}.zip ./*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ github.workspace }}/native/build/${{ matrix.artifact_name }}.zip

  release:
    name: Create GitHub Release
    needs: build-natives
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*.zip # Upload all zipped artifacts