name: inertia-test-ragdolls
main: com.ladakx.inertia.test.ragdolls.InertiaTestRagdollsPlugin
version: 1.0-DEV
api-version: "1.16"
depend: [ Inertia ]
commands:
  itragdoll:
    description: Spawn Inertia test ragdolls (via API)
    usage: /itragdoll spawn
    permission: inertia.test.ragdolls
permissions:
  inertia.test.ragdolls:
    default: op

